---
title: "about_draft1"
author: "Grace Pan"
date: "2/25/2020"
output: html_document
---

## Using Yelp to Analyze Date Spots in Popular Metropolitan Areas


 My final project entails using Yelp data to analyze the best date spots across various metropolitan areas in the United States and Canada. I am interested in learning about what types of activities are most popular for dates (descriptive) and why (causal/inferential). 
 
 In order to gather the data, I need to complete two steps: a) scraping Yelp data, and b) detecting strings of keywords relevant to date spots. 
 
 For my week 3 milestone, I tried many methods to scrape Yelp data. First, I used [this website]( https://billpetti.github.io/2017-12-23-use-yelp-api-r-rstats/) to attempt to use the Yelp API with R. I could not figure out how to get this to work. Second, I found a [dataset](https://www.yelp.com/dataset/download) provided by Yelp, but the problem was it was in JSON rather than R. It was also an enormous file that my computer was unable to process. Finally, I found [several CSV files](https://www.kaggle.com/yelp-dataset/yelp-dataset/data) including a subset of Yelp's business, reviews, and user data.  This is ultimately what I chose to work with.
 
 The Kaggle dataset has 5,200,000 user reviews, information on 174,000 businneses, and the data spans 11 metropolitan areas. This is too much data for my computer to process, so I used the IQSS computers in CGIS North (per Mitchell's suggestion) to filter for seven major cities to diminish the dataset in Excel. Although the cities included in this dataset (Montreal, QC; Madison, WI; Pittsburgh, PA; Toronto, ON; Cleveland, OH; Las Vegas, NV; and Charlotte, NC) are not the ones I anticipated researching, I am now looking forward to explore the use of Yelp in geographically diverse metropolitan cities across the US and Canada.
 
 After talking with Preceptor during his office hours Thursday morning, he approved my method for the milestone but encouraged me to wrestle with the Yelp dataset more before resorting to the Kaggle dataset, so I will work with the Yelp dataset for the milestone next week. 
 
 You can see the dataset in my [Github repo](https://github.com/gspan28/final_project_version1) in the gather.Rmd file. [This](https://www.kaggle.com/ambarish/a-very-extensive-data-analysis-of-yelp 
) is a good example of the type of analysis I want to do once I clean and combine the data. 

---

For my week 4 milestone, I talked to Mitchell, and he recommended I push forward with the Kaggle dataset until I find out whether this project is feasible or not with a subset of the data. If it is not feasible, then I don't need to waste time with the Yelp Json dataset. If it is feasible, then I can attempt to convert the Yelp Json dataset to be compatible with R. 

Using the Kaggle CSV files, I have successfully imported the business overview data into R, which includes restaurant ratings. This week, I browsed through the other CSV files and determined which ones would be most useful to me. Two files, yelp_tip and yelp_review will be useful because they will allow me to complete the second step of my project, detecting strings of keywords relevant to date spots.

This week, I imported the yelp_tip and yelp_review datasets in order to test if my workflow is feasible or not. Because the only common variable between datasets yelp_business, yelp_tip, and yelp_review is the business ID, I used full_join() function to merge these datasets.

Now, I have the merged datasets in order to conduct the next steps of my data analysis. 


 
